# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from pathlib import Path

sys.setrecursionlimit(5000)

block_cipher = None

datas = []
# Include entire sentinel package (core + tools + policies)
for root, dirs, files in os.walk("../sentinel"):
    dest = Path(root).relative_to("..").as_posix()
    datas.append((root, dest))

# Include plugins directory
for root, dirs, files in os.walk("plugins"):
    dest = Path(root).as_posix()
    if "__pycache__" not in dest:
        datas.append((root, dest))

a = Analysis(
    ['main.py'],
    pathex=['.', '..'],
    binaries=[],
    datas=datas,
    hiddenimports=[
        # FastAPI / uvicorn
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.middleware',
        'uvicorn.middleware.wsgi',
        'fastapi',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.datastructures',
        'pydantic',
        'pydantic_settings',
        'python_multipart',
        'yaml',
        'bcrypt',
        'cryptography',
        'PIL',
        'PIL.Image',
        'fitz',
        'reportlab',
        'docx',
        'git',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'aiosqlite',
        'jwt',
        'httptools',
        'watchfiles',
        'websockets',
        # App modules
        'sidecar.modules',
        'sidecar.modules.monitor',
        'sidecar.modules.executor',
        'sidecar.modules.ai_provider',
        'sidecar.modules.filesystem',
        'sidecar.modules.permissions',
        'sidecar.modules.permissions_memory',
        'sidecar.modules.audit',
        'sidecar.modules.proactive',
        'sidecar.modules.plugins',
        'sidecar.modules.fleet',
        'sidecar.modules.auth',
        'sidecar.modules.authorization',
        'sidecar.modules.sentinel_bridge',
        'sidecar.modules.security',
        'sidecar.modules.security.windows_acl',
        'sidecar.windows_acl',
        # Routers
        'sidecar.routers',
        'sidecar.routers.v1',
        'sidecar.routers.v1.execute',
        'sidecar.routers.v1.policies',
        'sidecar.routers.v1.audit',
        'sidecar.routers.v1.agents',
        # Services
        'sidecar.services',
        'sidecar.services.ai_service',
        'sidecar.services.audit_service',
        'sidecar.services.executor_service',
        'sidecar.services.filesystem_service',
        'sidecar.services.fleet_service',
        'sidecar.services.monitor_service',
        'sidecar.services.permissions_service',
        'sidecar.services.plugins_service',
        'sidecar.services.plugin_sandbox',
        'sidecar.services.proactive_service',
        'sidecar.services.rate_limiter',
        # Repositories
        'sidecar.repositories',
        'sidecar.repositories.database',
        'sidecar.repositories.ai_repository',
        'sidecar.repositories.audit_repository',
        'sidecar.repositories.fleet_repository',
        'sidecar.repositories.permissions_repository',
        # Sentinel
        'sentinel',
        'sentinel.core',
        'sentinel.core.tool',
        'sentinel.core.tool_gateway',
        'sentinel.core.policy',
        'sentinel.core.policy_engine',
        'sentinel.core.decision_engine',
        'sentinel.core.orchestrator',
        'sentinel.core.planner',
        'sentinel.core.intent',
        'sentinel.core.context',
        'sentinel.core.memory',
        'sentinel.core.operational_memory',
        'sentinel.core.capability_registry',
        'sentinel.core.quality_gate',
        'sentinel.core.model_router',
        'sentinel.core.goals',
        'sentinel.core.confirmation',
        'sentinel.core.integrations',
        'sentinel.core.observability',
        'sentinel.core.recovery',
        'sentinel.tools.integration_tools',
        'sentinel.tools',
        'sentinel.tools.system_tools',
        'sentinel.tools.ai_tools',
        'sentinel.tools.audit_tools',
        'sentinel.tools.fleet_tools',
        'sentinel.tools.permissions_tools',
        'sentinel.tools.plugins_tools',
        'sentinel.tools.proactive_tools',
        'sentinel.tools.sentinel_tools',
        'sentinel.policies',
        'sentinel.policies.loader',
        'sentinel.policies.security_policies',
        'sentinel.policies.output_policies',
        'sentinel.policies.schema',
        # fleet_server
        'fleet_server',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'cv2',
        'tensorflow',
        'torch',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='sidecar',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
