# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from pathlib import Path

sys.setrecursionlimit(5000)

block_cipher = None

# PyInstaller defines SPECPATH as the absolute directory of this spec file.
# All paths below are derived from it so the build is independent of CWD.
SPEC_DIR = os.path.abspath(SPECPATH)
REPO_DIR = os.path.dirname(SPEC_DIR)

datas = []
# Include entire sentinel package (core + tools + policies)
sentinel_dir = os.path.join(REPO_DIR, 'sentinel')
for root, dirs, files in os.walk(sentinel_dir):
    rel = os.path.relpath(root, REPO_DIR)
    dest = rel.replace('\\', '/')
    datas.append((root, dest))

# Include plugins directory
plugins_dir = os.path.join(SPEC_DIR, 'plugins')
if os.path.isdir(plugins_dir):
    for root, dirs, files in os.walk(plugins_dir):
        rel = os.path.relpath(root, SPEC_DIR)
        dest = rel.replace('\\', '/')
        if "__pycache__" not in dest:
            datas.append((root, dest))

a = Analysis(
    [os.path.join(SPEC_DIR, 'main.py')],
    pathex=[SPEC_DIR, REPO_DIR],
    binaries=[],
    datas=datas,
    hiddenimports=[
        # FastAPI / uvicorn
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.middleware',
        'uvicorn.middleware.wsgi',
        'fastapi',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.datastructures',
        'pydantic',
        'pydantic_settings',
        'python_multipart',
        'yaml',
        'bcrypt',
        'cryptography',
        'PIL',
        'PIL.Image',
        'fitz',
        'reportlab',
        'psutil',
        'docx',
        'git',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'aiosqlite',
        'jwt',
        'httptools',
        'watchfiles',
        'websockets',
        # App modules
        'modules',
        'modules.sidecar_supervision',
        'modules.monitor',
        'modules.executor',
        'modules.ai_provider',
        'modules.filesystem',
        'modules.permissions',
        'modules.permissions_memory',
        'modules.audit',
        'modules.proactive',
        'modules.plugins',
        'modules.fleet',
        'modules.auth',
        'modules.authorization',
        'modules.sentinel_bridge',
        'modules.admin',
        'modules.help',
        'modules.error_recovery',
        'modules.proactive',
        'modules.triggers',
        'modules.profile',
        'modules.security',
        'modules.security.windows_acl',
        'windows_acl',
        # Routers
        'routers',
        'routers.v1',
        'routers.v1.execute',
        'routers.v1.policies',
        'routers.v1.audit',
        'routers.v1.agents',
        'routers.v1.triggers',
        'routers.v1.profile',
        'routers.auth_jwt',
        'routers.continuations',
        # Services
        'services',
        'services.ai_service',
        'services.local_model_service',
        'services.audit_service',
        'services.executor_service',
        'services.filesystem_service',
        'services.fleet_service',
        'services.monitor_service',
        'services.permissions_service',
        'services.plugins_service',
        'services.plugin_sandbox',
        'services.proactive_service',
        'services.rate_limiter',
        'services.continuation_executor',
        'services.proactive_service',
        # Repositories
        'repositories',
        'repositories.database',
        'repositories.ai_repository',
        'repositories.audit_repository',
        'repositories.fleet_repository',
        'repositories.permissions_repository',
        'repositories.agent_repository',
        'repositories.async_engine',
        'repositories.cloud_authority_store',
        'repositories.user_preferences_store',
        'repositories.data_control_store',
        'repositories.execution_grant_repository',
        'modules.sentinel_lifecycle',
        # Sentinel
        'sentinel',
        'sentinel.core',
        'sentinel.core.tool',
        'sentinel.core.tool_gateway',
        'sentinel.core.policy',
        'sentinel.core.policy_engine',
        'sentinel.core.decision_engine',
        'sentinel.core.orchestrator',
        'sentinel.core.planner',
        'sentinel.core.intent',
        'sentinel.core.context',
        'sentinel.core.memory',
        'sentinel.core.operational_memory',
        'sentinel.core.capability_registry',
        'sentinel.core.quality_gate',
        'sentinel.core.model_router',
        'sentinel.core.goals',
        'sentinel.core.confirmation',
        'sentinel.core.integrations',
            'sentinel.core.recovery',
        'sentinel.core.skill',
        'sentinel.core.skill_engine',
        'sentinel.core.vault',
        'sentinel.core.user_profile',
        'sentinel.core.user_profile_async',
        'sentinel.core.content_security',
        'sentinel.core.network_monitor',
        'sentinel.core.offline_queue',
        'sentinel.core.hardening',
        'sentinel.core.agent',
            'sentinel.local_model',
        'sentinel.local_model.runtime',
        'sentinel.advisory',
            'sentinel.advisory.rules',
        'sentinel.tools.integration_tools',
        'sentinel.tools',
        'sentinel.tools.system_tools',
        'sentinel.tools.ai_tools',
        'sentinel.tools.audit_tools',
        'sentinel.tools.fleet_tools',
        'sentinel.tools.permissions_tools',
        'sentinel.tools.plugins_tools',
        'sentinel.tools.proactive_tools',
        'sentinel.tools.sentinel_tools',
        'sentinel.tools.agent_tools',
        'sentinel.tools.trigger_tools',
        'sentinel.tools.plugins_tools',
        'sentinel.tools.knowledge_base_tools',
        'sentinel.tools.file_pipeline_tools',
        'sentinel.tools.web_browsing_tools',
        'sentinel.tools.app_discovery_tool',
        'sentinel.tools.hardening_tools',
        'sentinel.tools.profile_tools',
        'sentinel.policies',
        'sentinel.policies.loader',
        'sentinel.policies.security_policies',
        'sentinel.policies.output_policies',
        'sentinel.policies.schema',
        # fleet_server
        'fleet_server',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'cv2',
        'tensorflow',
        'torch',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='sidecar',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
