from sentinel.models import ModelMetadata, ModelStatus
from sentinel.core.model_registry import ModelRegistry


def build_default_registry() -> ModelRegistry:
    registry = ModelRegistry()

    registry.register_many([
        ModelMetadata(
            id="deepseek/deepseek-v4-flash:free",
            provider="deepseek",
            context_window=128000,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            speed="fast",
            cost=0.0,
            local=False,
            status=ModelStatus.AVAILABLE,
            tags=["free", "chat", "coding"],
        ),
        ModelMetadata(
            id="nvidia/nemotron-3-super-120b-a12b",
            provider="nvidia-nemotron",
            context_window=128000,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            speed="medium",
            cost=0.0,
            local=False,
            status=ModelStatus.AVAILABLE,
            tags=["free", "reasoning"],
        ),
        ModelMetadata(
            id="Qwen3-1.7B-Q8_0.gguf",
            provider="sentinel_local",
            context_window=4096,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=False,
            speed="slow",
            cost=0.0,
            local=True,
            status=ModelStatus.AVAILABLE,
            tags=["local", "small"],
        ),
        ModelMetadata(
            id="llama3",
            provider="ollama",
            context_window=8192,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            speed="medium",
            cost=0.0,
            local=True,
            status=ModelStatus.AVAILABLE,
            tags=["local", "ollama"],
        ),
        ModelMetadata(
            id="gpt-4o",
            provider="openai",
            context_window=128000,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            supports_vision=True,
            speed="fast",
            cost=0.0,
            local=False,
            status=ModelStatus.AVAILABLE,
            tags=["paid", "fast"],
        ),
        ModelMetadata(
            id="gpt-4o-mini",
            provider="github_models",
            context_window=128000,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            speed="fast",
            cost=0.0,
            local=False,
            status=ModelStatus.AVAILABLE,
            tags=["free", "fast", "small"],
        ),
        ModelMetadata(
            id="gemini-2.5-flash",
            provider="gemini",
            context_window=1000000,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            supports_vision=True,
            speed="fast",
            cost=0.0,
            local=False,
            status=ModelStatus.AVAILABLE,
            tags=["free", "fast", "vision"],
        ),
        ModelMetadata(
            id="claude-sonnet-4",
            provider="anthropic",
            context_window=200000,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            speed="fast",
            cost=0.0,
            local=False,
            status=ModelStatus.AVAILABLE,
            tags=["paid", "reasoning"],
        ),
        ModelMetadata(
            id="llama-3.3-70b-versatile",
            provider="groq",
            context_window=32768,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            speed="very_fast",
            cost=0.0,
            local=False,
            status=ModelStatus.AVAILABLE,
            tags=["free", "fast", "groq"],
        ),
        ModelMetadata(
            id="llama-3.3-70b",
            provider="cerebras",
            context_window=8192,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            speed="very_fast",
            cost=0.0,
            local=False,
            status=ModelStatus.AVAILABLE,
            tags=["free", "fast", "cerebras"],
        ),
        ModelMetadata(
            id="mistral-small-latest",
            provider="mistral",
            context_window=32768,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            speed="fast",
            cost=0.0,
            local=False,
            status=ModelStatus.AVAILABLE,
            tags=["free", "mistral"],
        ),
        ModelMetadata(
            id="mistral-large-latest",
            provider="mistral",
            context_window=128000,
            supports_tool_calling=False,
            supports_coding=True,
            supports_reasoning=True,
            speed="fast",
            cost=0.0,
            local=False,
            status=ModelStatus.AVAILABLE,
            tags=["paid", "mistral", "reasoning"],
        ),
    ])

    return registry


_DEFAULT_REGISTRY: ModelRegistry | None = None


def get_default_registry() -> ModelRegistry:
    global _DEFAULT_REGISTRY
    if _DEFAULT_REGISTRY is None:
        _DEFAULT_REGISTRY = build_default_registry()
    return _DEFAULT_REGISTRY
